# Generated by Django 3.1 on 2020-08-06 11:17

from django.db import migrations, models


def populate_original_day_field(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    ScheduledPayment = apps.get_model('transfer', 'ScheduledPayment')
    for payment in ScheduledPayment.objects.using(db_alias).filter(original_day__isnull=True):
        payment.original_day = payment.original_day.next_payment_date.day
        payment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_scheduledpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpayment',
            name='original_day',
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(populate_original_day_field, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='scheduledpayment',
            name='original_day',
            field=models.IntegerField(),
        )
    ]
