# Generated by Django 3.1 on 2020-08-06 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_owner'),
        ('transfer', '0003_scheduledpayment_original_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfer',
            name='is_outbound',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='TransferMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=128)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_meta', to='account.account')),
            ],
        ),
    ]
